#! /bin/sh
#
# $Id: massage,v 1.3 2016/01/06 03:36:56 setlorg Exp $
#
# A crude form of tokenization, resulting in lines
# consisting of one tuple of strings each.  Best used
# only after you have already arranged for one "thing"
# (e.g. function or type declaration) per line.

# default sed is sed unless SED is in the envt
: ${SED:=sed}
$SED -e 's/#.*$//' \
     -e "s/[][)(}{><,;=\*]/ '&' /g" \
     -e "s/[A-Za-z0-9_][A-Za-z0-9_+]*/'&'/g" \
     -e 's/^.*$/[&]/'
