.\" $Id: setltran.1,v 1.5 2022/03/21 00:13:50 setlorg Exp $
.TH SETLTRAN "1" "May 2022" "setltran" "User Commands"
.SH NAME
setltran \- the GNU SETL Translator
.SH SYNOPSIS
.B setltran
[\fIOPTIONS\fR] [\fIFILENAME\fR | \fISTRING\fR | \fB-\fR]
.SH DESCRIPTION
The GNU SETL Translator (Compiler).
.PP
Try
.B setltran \-\-help
for brief help, and
.B info setltran
for longer Texinfo-based help at the terminal.
.PP
See also
.I https://setl.org/setl/doc/
or local shares for guides in PDF and HTML.
